### ISSUE TITLE
Feedback zum Testat

### ISSUE THREAD

**Issue by thomsmits** [tpe-lecture/repo-05#1]
Bitte korrigieren Sie die folgenden Fehler und checken Sie dann die korrigierte Version ein. Danach können Sie dieses Issue schließen.

  * JavaDoc ergänzen, diese fehlt vollständig
  * Ihre Implementierung geht nicht richtig mit Eingaben um, die ungültige Zeichen enthalten. Diese sollen stillschweigend entfernt werden.
  * Entfernen Sie alle TODO-Kommentare

**Comment by Beggattron** [comment]
Habe die vorgegebenen Fehler korrigiert und gepusht.
Habe allerdings die selben Änderungen nun 2-3x gepusht, da ich anfangs einen "push rejected non-fast-forward" Fehler angezeigt bekommen habe.
